### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by trungtran61** [ulvesked/nativescript-rsa#1]
tns plugin add nativescript-rsa
npm ERR! code E404
npm ERR! 404 Not Found: nativescript-rsa@latest

**Comment by ulvesked** [comment]
Hi, 
That's because this plugin is not published to npm. I am still testing and fixing bugs, but I can try to publish a beta release to npm this weekend.

**Comment by ulvesked** [comment]
I have now made a release on github.
This can be installed with 

    tns plugin add https://github.com/ulvesked/nativescript-rsa/releases/download/v1.0.1-beta.0/nativescript-rsa-1.0.1-beta.0.tgz 

Later this weekend I will attempt to publish this beta to npm also.

**Comment by trungtran61** [comment]
Thanks so much for you quick help. Trung. On Apr 18, 2019 12:22 AM, ulvesked <notifications@github.com> wrote:I have now made a release on github.
This can be installed with
tns plugin add https://github.com/ulvesked/nativescript-rsa/releases/download/v1.0.1-beta.0/nativescript-rsa-1.0.1-beta.0.tgz 

Later this weekend I will attempt to publish this beta to npm also.

**Comment by trungtran61** [comment]
Hi
I tried running the sample code and I got the below:
var key = rsa.generateKey("org.nativescript.my-app.rsa-key", 2048);var message = "Hello world";var signature = rsa.sign(message, key, RsaHashAlgorithm.SHA1);console.log('signature is ' + signature);var isValid = rsa.verify(signature, message, key, RsaHashAlgorithm.SHA1);console.log('signature is valid = ' + isValid);
CONSOLE LOG file:///app/tns_modules/nativescript-rsa/rsa.js:110:28: Key returned: <SecKeyRef algorithm id: 1, key type: RSAPrivateKey, version: 4, block size: 2048 bits, addr: 0x600003178c60>CONSOLE LOG file:///app/app/home/home.component.js:47:20: signature is [object ArrayBuffer]CONSOLE LOG file:///app/tns_modules/nativescript-rsa/rsa.js:144:24: [object ArrayBuffer] Hello world {"_secKeyRef": {}} algid:sign:RSA:message-PKCS1v15:SHA1CONSOLE WARN file:///app/tns_modules/nativescript-rsa/rsa.js:156:29: Rsa.verify failed with error <Reference: 0x6000033f0e40>CONSOLE LOG file:///app/app/home/home.component.js:49:20: signature is valid = null

    On Thursday, April 18, 2019, 3:22:41 AM EDT, ulvesked <notifications@github.com> wrote:  
 
 
I have now made a release on github.
This can be installed with
tns plugin add https://github.com/ulvesked/nativescript-rsa/releases/download/v1.0.1-beta.0/nativescript-rsa-1.0.1-beta.0.tgz 

Later this weekend I will attempt to publish this beta to npm also.

**Comment by gabrielbiga** [comment]
Please publish in the NPM @ulvesked. My team and I are working to stabilize the plugin in the Android platform.
Thanks!

**Comment by ulvesked** [comment]
Hi,

This plugin is now published to NPM with your pull requests merged. Thanks for your contributions. 

@trungtran61 I have made several improvments to the iOS version. It should work better now than the first beta release.

**Comment by trungtran61** [comment]
I installed and ran the code provided. Still getting an error. Please advise thanks.

CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:16874:24: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:16874:24: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file:///app/tns_modules/nativescript-rsa/rsa.js:110:28: Key returned:  <SecKeyRef algorithm id: 1, key type: RSAPrivateKey, version: 4, block size: 2048 bits, addr: 0x600002a83400>
CONSOLE LOG file:///app/app/home/home.component.js:17:20: signature is [object ArrayBuffer]
CONSOLE LOG file:///app/tns_modules/nativescript-rsa/rsa.js:144:24: [object ArrayBuffer] Hello world {
"_secKeyRef": {}
} algid:sign:RSA:message-PKCS1v15:SHA256
CONSOLE WARN file:///app/tns_modules/nativescript-rsa/rsa.js:156:29: Rsa.verify failed with error The operation couldn’t be completed. (OSStatus error -67808 - RSA signature verification failed, no match)
CONSOLE LOG file:///app/app/home/home.component.js:19:20: signature is valid = null

**Comment by trungtran61** [comment]
Never mind, I got it working. Thanks for your hardwork.
