### ISSUE TITLE
Public Key on IOS incorrect format

### ISSUE THREAD

**Issue by dbligh** [ulvesked/nativescript-rsa#5]
### Which platform(s) does your issue occur on?
- iOS
- iOS - All (IOS 10, 13)
- emulator or device. What type of device? - Both physical iPhone5 and iPhone 11 Simulatir

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
```
"tns-ios": {
            "version": "6.3.0"
        },
        "tns-android": {
            "version": "6.3.0"
        }
```
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
The Public Key that gets generated from IOS using this library doesn't appear to be a valid format. When I try to export this and use it on another system (using Node crypto), I am getting errors about ASN1 headers being too long:

```
{
    "errorType": "Error",
    "errorMessage": "error:0D07209B:asn1 encoding routines:ASN1_get_object:too long",
    "code": "ERR_OSSL_ASN1_TOO_LONG",
    "opensslErrorStack": [
        "error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error",
        "error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error",
        "error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header"
    ],
    "library": "asn1 encoding routines",
    "function": "ASN1_get_object",
    "reason": "too long",
    "stack": [
        "Error: error:0D07209B:asn1 encoding routines:ASN1_get_object:too long",
        "    at Verify.verify (internal/crypto/sig.js:183:24)",
        "    at Runtime.v [as handler] (/var/task/controllers/random.js:1:36288)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

Here is a sample key that was generated from my IOS device:

```
-----BEGIN PUBLIC KEY-----
MIICITANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqJOhj8F7cR/3UfL65z5Y
OyqYH3adEgu2xEfn2tZzySAC8DJSz2KvAgpI7aFj5v5hXUNTiZA53XTf1OWbnD9u
bi3M1npafRgjW38wonf47nj11kApcb+HMKbO21xEybU+aXGKCRBH+MLQFn+5jKNM
tjjWqQJFBTyXAMYgl/4nN6sfU2lvvfYaDdAYgXI6diiRvuR/vgbNVxZL2SnMQK4/
SK/UraZ560F7TH3MajeUElroX2OJLIO2LqmGO2ifm/8PT9AlBop5JsberCxQtZl3
PH+cEhVEAV8ZxkFg5fwXT8OURW94GD0B0hopURq4K0LaT7Dhdn9TPQUYA7R0Be6y
sMBgPk2ZBb4EyIQ+KeddsieSgVRUtgE3yjLJVanifH23z5egr40PrA3XfU6NovNk
TLJbjmQ2/3TebxlNlsFeN9rijIV44QR/nsk2B99DXTNwl48mvyrTYYl/dCS9r6yx
UL3J85Kc9x6G/x0oi2NMMRFivxegEMcfRaA6k8tUOdrSLX6GTL1jpBPcubG1QDZR
MVJ+ShTEXotSivL5aBA9FPSlrRis9dejvaoswDRvG+aptpeOYCeM/AARgLePIY9m
khUPqixZRKmuBa+NDOS8AgNj+ENRTUukQYor3qih0/oMJdrTwxPaM1amzLE8SeQf
pokgtdJk261JnJJiPKLxwzUCAwEAAQ==
-----END PUBLIC KEY-----
```

When I run this key though a validator, I get an error:
```
java.lang.Exception: Error Performing Parsing java.lang.Exception: java.lang.IllegalArgumentException: failed to construct sequence from byte[]: DEF length 527 object truncated by 1 
```

I noticed there is an IOS helper project that is performing some manipulation of the public key (https://github.com/ulvesked/RsaHelper.git) but I can't make much sense of it.

Additionally, when I run the sample code on the README, it doesn't appear to work either on IOS:

Code:
```
var rsa = new Rsa();
        var key = rsa.generateKey("com.gen.mobile.rsa-key", 2048, true);
        var message = "Hello world";
        var signature = rsa.sign(message, key, RsaHashAlgorithm.SHA256);
        console.log('signature is ' + signature);
        var isValid = rsa.verify(signature, message, key, RsaHashAlgorithm.SHA256);
        console.log('signature is valid = ' + isValid);
```

Log:
```
2020-09-09 15:22:08.810418+1000 genmobileapp[646:286926] CONSOLE LOG file:///app/vendor.js:162814:28: Key returned:  <SecKeyRef algorithm id: 1, key type: RSAPrivateKey, version: 4, block size: 2048 bits, addr: 0x166cd6a0>

CONSOLE LOG file:///app/vendor.js:162814:28: Key returned:  <SecKeyRef algorithm id: 1, key type: RSAPrivateKey, version: 4, block size: 2048 bits, addr: 0x166cd6a0>
2020-09-09 15:22:08.865452+1000 genmobileapp[646:286926] CONSOLE LOG file:///app/2.js:222:20: signature is [object ArrayBuffer]

CONSOLE LOG file:///app/2.js:222:20: signature is [object ArrayBuffer]
2020-09-09 15:22:08.866968+1000 genmobileapp[646:286926] CONSOLE LOG file:///app/vendor.js:162848:24: [object ArrayBuffer] Hello world {
  "_secKeyRef": {}
} algid:sign:RSA:message-PKCS1v15:SHA256

CONSOLE LOG file:///app/vendor.js:162848:24: [object ArrayBuffer] Hello world {
  "_secKeyRef": {}
} algid:sign:RSA:message-PKCS1v15:SHA256
2020-09-09 15:22:08.926772+1000 genmobileapp[646:286926] CONSOLE WARN file:///app/vendor.js:162860:29: Rsa.verify failed with error The operation couldn’t be completed. (OSStatus error -67808 - RSA signature verification failed, no match)

CONSOLE WARN file:///app/vendor.js:162860:29: Rsa.verify failed with error The operation couldn’t be completed. (OSStatus error -67808 - RSA signature verification failed, no match)
2020-09-09 15:22:08.927207+1000 genmobileapp[646:286926] CONSOLE LOG file:///app/2.js:224:20: signature is valid = null

CONSOLE LOG file:///app/2.js:224:20: signature is valid = null
```

Worth noting, everything works fine in Android. Appreciate any assistance you can offer.

Thanks,
Dan

**Comment by ulvesked** [comment]
Hi Dan, 

This is most likely an issue in the RsaHelper. 
I recall experiencing a something similar to this earlier this year and it should be a relatively minor fix. I will look in to it. 

Some day I might replace the RsaHelper with a pure JS encoding/decoding since iOS does not natively support PEM-encodings.

**Comment by dbligh** [comment]
Thank you! Let me know if you would prefer me to raise this issue on the RsaHelper repo instead?

**Comment by jalcine** [comment]
Bumping this because I’m planning to use this in a [project of mine](https://indieweb.org/Fortress) and this would be a show stopper.

(Originally published at: https://v2.jacky.wtf/post/4a57948d-35ff-4d7e-b34c-502172165bb2)

**Comment by keithoys** [comment]
Issue still persists. 

Here is the result after running sample code:

```
CONSOLE LOG: Key returned:  <SecKeyRef algorithm id: 1, key type: RSAPrivateKey, version: 4, block size: 2048 bits, addr: 0x60000143b1e0>
CONSOLE LOG: signature is [object ArrayBuffer]
CONSOLE LOG: [object ArrayBuffer] Hello world {
"_secKeyRef": {}
} algid:sign:RSA:message-PKCS1v15:SHA256
CONSOLE WARN: Rsa.verify failed with error The operation couldn’t be completed. (OSStatus error -67808 - RSA signature verification failed, no match)
CONSOLE LOG: signature is valid = null
```

Environment:

**iOS**
14.5

**node -v**
14.15.0

**npm -v**
6.14.8

**tns -v**
8.0.1

**nativescript -v**
8.0.1

@ulvesked Appreciate your kind assistance!

**Comment by keithoys** [comment]
> Some day I might replace the RsaHelper with a pure JS encoding/decoding since iOS does not natively support PEM-encodings.

Hello @ulvesked I can see that the following has been committed to the project `Add pure JS implementation and remove RsaHelper` - which I suppose fixes this issue. However, there is no new release. Appreciate your help on this as I intend to use this in my project!

**Comment by keithoys** [comment]
Please help @ulvesked 🙏🏻

**Comment by ulvesked** [comment]
Hi @keithoys 
Sorry for the delay. I am no longer working with the project where this tool was being used. I have now upgraded to latest NS version and published to NPM. This also includes the release of "nativescript-base64" https://github.com/ulvesked/nativescript-base64.
